"""Add message column to swap_requests

Revision ID: 00fe333beef0
Revises: 
Create Date: 2025-11-05 16:04:12.265951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fe333beef0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_requests', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
